# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ciktiAl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ciktiAl(object):
    def setupUi(self, ciktiAl):
        ciktiAl.setObjectName("ciktiAl")
        ciktiAl.resize(707, 589)
        self.dersSec_cmb = QtWidgets.QComboBox(ciktiAl)
        self.dersSec_cmb.setGeometry(QtCore.QRect(130, 150, 171, 31))
        self.dersSec_cmb.setObjectName("dersSec_cmb")
        self.konuSec_cmb = QtWidgets.QComboBox(ciktiAl)
        self.konuSec_cmb.setGeometry(QtCore.QRect(400, 150, 171, 31))
        self.konuSec_cmb.setObjectName("konuSec_cmb")
        self.dersSec_lbl = QtWidgets.QLabel(ciktiAl)
        self.dersSec_lbl.setGeometry(QtCore.QRect(170, 110, 101, 21))
        self.dersSec_lbl.setObjectName("dersSec_lbl")
        self.konuSec_lbl = QtWidgets.QLabel(ciktiAl)
        self.konuSec_lbl.setGeometry(QtCore.QRect(450, 110, 101, 21))
        self.konuSec_lbl.setObjectName("konuSec_lbl")
        self.label_3 = QtWidgets.QLabel(ciktiAl)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 91, 41))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(ciktiAl)
        self.label_5.setGeometry(QtCore.QRect(100, 260, 71, 41))
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(ciktiAl)
        self.textBrowser.setGeometry(QtCore.QRect(350, 210, 41, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(ciktiAl)
        self.label_4.setGeometry(QtCore.QRect(270, 210, 71, 41))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(ciktiAl)
        self.label_6.setGeometry(QtCore.QRect(470, 210, 81, 41))
        self.label_6.setObjectName("label_6")
        self.textBrowser_3 = QtWidgets.QTextBrowser(ciktiAl)
        self.textBrowser_3.setGeometry(QtCore.QRect(550, 210, 41, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_7 = QtWidgets.QLabel(ciktiAl)
        self.label_7.setGeometry(QtCore.QRect(470, 260, 81, 41))
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(ciktiAl)
        self.textBrowser_2.setGeometry(QtCore.QRect(350, 260, 41, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_8 = QtWidgets.QLabel(ciktiAl)
        self.label_8.setGeometry(QtCore.QRect(270, 260, 71, 41))
        self.label_8.setObjectName("label_8")
        self.textBrowser_4 = QtWidgets.QTextBrowser(ciktiAl)
        self.textBrowser_4.setGeometry(QtCore.QRect(550, 260, 41, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton = QtWidgets.QPushButton(ciktiAl)
        self.pushButton.setGeometry(QtCore.QRect(440, 530, 261, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_5 = QtWidgets.QTextBrowser(ciktiAl)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 320, 691, 192))
        self.textBrowser_5.setObjectName("textBrowser_5")

        self.retranslateUi(ciktiAl)
        QtCore.QMetaObject.connectSlotsByName(ciktiAl)

    def retranslateUi(self, ciktiAl):
        _translate = QtCore.QCoreApplication.translate
        ciktiAl.setWindowTitle(_translate("ciktiAl", "stats"))
        self.dersSec_lbl.setText(_translate("ciktiAl", "Ders Seç"))
        self.konuSec_lbl.setText(_translate("ciktiAl", "Konu Seç"))
        self.label_3.setText(_translate("ciktiAl", "Konuya göre:"))
        self.label_5.setText(_translate("ciktiAl", "Derse göre:"))
        self.label_4.setText(_translate("ciktiAl", "dogru sayisi:"))
        self.label_6.setText(_translate("ciktiAl", "yanlis sayisi:"))
        self.label_7.setText(_translate("ciktiAl", "yanlis sayisi:"))
        self.label_8.setText(_translate("ciktiAl", "dogru sayisi:"))
        self.pushButton.setText(_translate("ciktiAl", "Çıktı Al"))
