# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SifreUnut.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SifreUnuttum(object):
    def setupUi(self, SifreUnuttum):
        SifreUnuttum.setObjectName("SifreUnuttum")
        SifreUnuttum.resize(661, 488)
        self.lblGuvenlik = QtWidgets.QLabel(SifreUnuttum)
        self.lblGuvenlik.setGeometry(QtCore.QRect(160, 150, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGuvenlik.setFont(font)
        self.lblGuvenlik.setObjectName("lblGuvenlik")
        self.labelYeniSifre = QtWidgets.QLabel(SifreUnuttum)
        self.labelYeniSifre.setGeometry(QtCore.QRect(220, 260, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelYeniSifre.setFont(font)
        self.labelYeniSifre.setObjectName("labelYeniSifre")
        self.lblKullanici = QtWidgets.QLabel(SifreUnuttum)
        self.lblKullanici.setGeometry(QtCore.QRect(240, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblKullanici.setFont(font)
        self.lblKullanici.setObjectName("lblKullanici")
        self.txtKullanici = QtWidgets.QLineEdit(SifreUnuttum)
        self.txtKullanici.setGeometry(QtCore.QRect(180, 100, 261, 41))
        self.txtKullanici.setText("")
        self.txtKullanici.setObjectName("txtKullanici")
        self.txtGuvenlik = QtWidgets.QLineEdit(SifreUnuttum)
        self.txtGuvenlik.setGeometry(QtCore.QRect(180, 210, 261, 41))
        self.txtGuvenlik.setText("")
        self.txtGuvenlik.setObjectName("txtGuvenlik")
        self.txtYeniSifre = QtWidgets.QLineEdit(SifreUnuttum)
        self.txtYeniSifre.setGeometry(QtCore.QRect(180, 330, 261, 41))
        self.txtYeniSifre.setText("")
        self.txtYeniSifre.setObjectName("txtYeniSifre")
        self.btnSifreDegis = QtWidgets.QPushButton(SifreUnuttum)
        self.btnSifreDegis.setGeometry(QtCore.QRect(240, 400, 141, 51))
        self.btnSifreDegis.setObjectName("btnSifreDegis")

        self.retranslateUi(SifreUnuttum)
        QtCore.QMetaObject.connectSlotsByName(SifreUnuttum)

    def retranslateUi(self, SifreUnuttum):
        _translate = QtCore.QCoreApplication.translate
        SifreUnuttum.setWindowTitle(_translate("SifreUnuttum", "Form"))
        self.lblGuvenlik.setText(_translate("SifreUnuttum", "Guvenlik Sorunuzun Cevabını Giriniz"))
        self.labelYeniSifre.setText(_translate("SifreUnuttum", "Yeni Sifrenizi Giriniz"))
        self.lblKullanici.setText(_translate("SifreUnuttum", " Kullanici Adiniz"))
        self.btnSifreDegis.setText(_translate("SifreUnuttum", "Sifreni Degistir"))
