# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sigma.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sigma(object):
    def setupUi(self, sigma):
        sigma.setObjectName("sigma")
        sigma.resize(1148, 996)
        self.submit_btn = QtWidgets.QPushButton(sigma)
        self.submit_btn.setGeometry(QtCore.QRect(140, 950, 901, 41))
        self.submit_btn.setObjectName("submit_btn")
        self.c_radio = QtWidgets.QRadioButton(sigma)
        self.c_radio.setGeometry(QtCore.QRect(110, 680, 16, 91))
        self.c_radio.setText("")
        self.c_radio.setObjectName("c_radio")
        self.a_radio = QtWidgets.QRadioButton(sigma)
        self.a_radio.setGeometry(QtCore.QRect(110, 440, 16, 101))
        self.a_radio.setText("")
        self.a_radio.setObjectName("a_radio")
        self.b_radio = QtWidgets.QRadioButton(sigma)
        self.b_radio.setGeometry(QtCore.QRect(110, 560, 16, 91))
        self.b_radio.setText("")
        self.b_radio.setObjectName("b_radio")
        self.d_radio = QtWidgets.QRadioButton(sigma)
        self.d_radio.setGeometry(QtCore.QRect(110, 800, 16, 91))
        self.d_radio.setText("")
        self.d_radio.setObjectName("d_radio")
        self.a_lbl = QtWidgets.QLabel(sigma)
        self.a_lbl.setGeometry(QtCore.QRect(70, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a_lbl.setFont(font)
        self.a_lbl.setObjectName("a_lbl")
        self.b_lbl = QtWidgets.QLabel(sigma)
        self.b_lbl.setGeometry(QtCore.QRect(70, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b_lbl.setFont(font)
        self.b_lbl.setObjectName("b_lbl")
        self.c_lbl = QtWidgets.QLabel(sigma)
        self.c_lbl.setGeometry(QtCore.QRect(70, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c_lbl.setFont(font)
        self.c_lbl.setObjectName("c_lbl")
        self.d_lbl = QtWidgets.QLabel(sigma)
        self.d_lbl.setGeometry(QtCore.QRect(70, 830, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.d_lbl.setFont(font)
        self.d_lbl.setObjectName("d_lbl")
        self.a_txt = QtWidgets.QTextBrowser(sigma)
        self.a_txt.setGeometry(QtCore.QRect(140, 460, 901, 71))
        self.a_txt.setObjectName("a_txt")
        self.b_txt = QtWidgets.QTextBrowser(sigma)
        self.b_txt.setGeometry(QtCore.QRect(140, 580, 901, 71))
        self.b_txt.setObjectName("b_txt")
        self.c_txt = QtWidgets.QTextBrowser(sigma)
        self.c_txt.setGeometry(QtCore.QRect(140, 700, 901, 71))
        self.c_txt.setObjectName("c_txt")
        self.d_txt = QtWidgets.QTextBrowser(sigma)
        self.d_txt.setGeometry(QtCore.QRect(140, 820, 901, 71))
        self.d_txt.setObjectName("d_txt")
        self.question_txt = QtWidgets.QTextBrowser(sigma)
        self.question_txt.setGeometry(QtCore.QRect(140, 341, 901, 81))
        self.question_txt.setObjectName("question_txt")
        self.image_lbl = QtWidgets.QLabel(sigma)
        self.image_lbl.setGeometry(QtCore.QRect(140, 20, 901, 311))
        self.image_lbl.setText("")
        self.image_lbl.setObjectName("image_lbl")
        self.answer_txt = QtWidgets.QLabel(sigma)
        self.answer_txt.setGeometry(QtCore.QRect(60, 950, 71, 31))
        self.answer_txt.setText("")
        self.answer_txt.setObjectName("answer_txt")

        self.retranslateUi(sigma)
        QtCore.QMetaObject.connectSlotsByName(sigma)

    def retranslateUi(self, sigma):
        _translate = QtCore.QCoreApplication.translate
        sigma.setWindowTitle(_translate("sigma", "sigma sınav"))
        self.submit_btn.setText(_translate("sigma", "Submit"))
        self.a_lbl.setText(_translate("sigma", "A"))
        self.b_lbl.setText(_translate("sigma", "B"))
        self.c_lbl.setText(_translate("sigma", "C"))
        self.d_lbl.setText(_translate("sigma", "D"))
