# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signUp(object):
    def setupUi(self, signUp):
        signUp.setObjectName("signUp")
        signUp.resize(548, 484)
        self.lblKullaniciTip = QtWidgets.QLabel(signUp)
        self.lblKullaniciTip.setGeometry(QtCore.QRect(120, 100, 150, 30))
        self.lblKullaniciTip.setObjectName("lblKullaniciTip")
        self.lbliSim = QtWidgets.QLabel(signUp)
        self.lbliSim.setGeometry(QtCore.QRect(120, 140, 150, 30))
        self.lbliSim.setObjectName("lbliSim")
        self.lblSoyisim = QtWidgets.QLabel(signUp)
        self.lblSoyisim.setGeometry(QtCore.QRect(120, 180, 150, 30))
        self.lblSoyisim.setObjectName("lblSoyisim")
        self.lblKullaniciAd = QtWidgets.QLabel(signUp)
        self.lblKullaniciAd.setGeometry(QtCore.QRect(120, 220, 150, 30))
        self.lblKullaniciAd.setObjectName("lblKullaniciAd")
        self.lblSifre = QtWidgets.QLabel(signUp)
        self.lblSifre.setGeometry(QtCore.QRect(120, 260, 150, 30))
        self.lblSifre.setObjectName("lblSifre")
        self.lblGuvenlik = QtWidgets.QLabel(signUp)
        self.lblGuvenlik.setGeometry(QtCore.QRect(120, 300, 151, 30))
        self.lblGuvenlik.setObjectName("lblGuvenlik")
        self.cmbKullaniciTip = QtWidgets.QComboBox(signUp)
        self.cmbKullaniciTip.setGeometry(QtCore.QRect(240, 100, 151, 22))
        self.cmbKullaniciTip.setObjectName("cmbKullaniciTip")
        self.cmbKullaniciTip.addItem("")
        self.cmbKullaniciTip.addItem("")
        self.cmbKullaniciTip.addItem("")
        self.txtiSim = QtWidgets.QLineEdit(signUp)
        self.txtiSim.setGeometry(QtCore.QRect(240, 140, 113, 22))
        self.txtiSim.setObjectName("txtiSim")
        self.txtSoyisim = QtWidgets.QLineEdit(signUp)
        self.txtSoyisim.setGeometry(QtCore.QRect(240, 180, 113, 22))
        self.txtSoyisim.setObjectName("txtSoyisim")
        self.txtKullaniciAd = QtWidgets.QLineEdit(signUp)
        self.txtKullaniciAd.setGeometry(QtCore.QRect(240, 220, 113, 22))
        self.txtKullaniciAd.setObjectName("txtKullaniciAd")
        self.txtSifre = QtWidgets.QLineEdit(signUp)
        self.txtSifre.setGeometry(QtCore.QRect(240, 260, 113, 22))
        self.txtSifre.setObjectName("txtSifre")
        self.cmbGuvenlik = QtWidgets.QComboBox(signUp)
        self.cmbGuvenlik.setGeometry(QtCore.QRect(270, 300, 181, 22))
        self.cmbGuvenlik.setObjectName("cmbGuvenlik")
        self.cmbGuvenlik.addItem("")
        self.cmbGuvenlik.addItem("")
        self.cmbGuvenlik.addItem("")
        self.cmbGuvenlik.addItem("")
        self.lblGubenlikAnswer = QtWidgets.QLabel(signUp)
        self.lblGubenlikAnswer.setGeometry(QtCore.QRect(120, 340, 161, 30))
        self.lblGubenlikAnswer.setObjectName("lblGubenlikAnswer")
        self.txtGuvenlikAnswer = QtWidgets.QLineEdit(signUp)
        self.txtGuvenlikAnswer.setGeometry(QtCore.QRect(290, 340, 191, 22))
        self.txtGuvenlikAnswer.setObjectName("txtGuvenlikAnswer")
        self.pushButton = QtWidgets.QPushButton(signUp)
        self.pushButton.setGeometry(QtCore.QRect(380, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(signUp)
        QtCore.QMetaObject.connectSlotsByName(signUp)

    def retranslateUi(self, signUp):
        _translate = QtCore.QCoreApplication.translate
        signUp.setWindowTitle(_translate("signUp", "Form"))
        self.lblKullaniciTip.setText(_translate("signUp", "Kullanici Tipi"))
        self.lbliSim.setText(_translate("signUp", "İsim"))
        self.lblSoyisim.setText(_translate("signUp", "Soyisim"))
        self.lblKullaniciAd.setText(_translate("signUp", "Kullanici Adi"))
        self.lblSifre.setText(_translate("signUp", "Sifre"))
        self.lblGuvenlik.setText(_translate("signUp", "Guvenlik Sorusu Seciniz:"))
        self.cmbKullaniciTip.setItemText(0, _translate("signUp", "admin"))
        self.cmbKullaniciTip.setItemText(1, _translate("signUp", "sinav sorumlusu"))
        self.cmbKullaniciTip.setItemText(2, _translate("signUp", "ogrenci"))
        self.cmbGuvenlik.setItemText(0, _translate("signUp", "ilkokul ogretmeninizin adi"))
        self.cmbGuvenlik.setItemText(1, _translate("signUp", "evcil hayvaninizin adi"))
        self.cmbGuvenlik.setItemText(2, _translate("signUp", "en sevdiginiz renk"))
        self.cmbGuvenlik.setItemText(3, _translate("signUp", "diger (özel güvenlik önlemi)"))
        self.lblGubenlikAnswer.setText(_translate("signUp", "Guvenlik Sorusunun Cevabı:"))
        self.pushButton.setText(_translate("signUp", "Kayit ol"))
