# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentEntryPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentEntry(object):
    def setupUi(self, StudentEntry):
        StudentEntry.setObjectName("StudentEntry")
        StudentEntry.resize(732, 704)
        self.calendar = QtWidgets.QCalendarWidget(StudentEntry)
        self.calendar.setGeometry(QtCore.QRect(160, 180, 411, 221))
        self.calendar.setObjectName("calendar")
        self.welcome_lbl = QtWidgets.QLabel(StudentEntry)
        self.welcome_lbl.setGeometry(QtCore.QRect(200, 60, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_lbl.setFont(font)
        self.welcome_lbl.setText("")
        self.welcome_lbl.setObjectName("welcome_lbl")
        self.zayifKonu_btn = QtWidgets.QPushButton(StudentEntry)
        self.zayifKonu_btn.setGeometry(QtCore.QRect(410, 460, 161, 41))
        self.zayifKonu_btn.setObjectName("zayifKonu_btn")
        self.sigma_btn = QtWidgets.QPushButton(StudentEntry)
        self.sigma_btn.setGeometry(QtCore.QRect(160, 460, 161, 41))
        self.sigma_btn.setObjectName("sigma_btn")
        self.istatistik_btn = QtWidgets.QPushButton(StudentEntry)
        self.istatistik_btn.setGeometry(QtCore.QRect(160, 530, 161, 41))
        self.istatistik_btn.setObjectName("istatistik_btn")
        self.ayarlar_btn = QtWidgets.QPushButton(StudentEntry)
        self.ayarlar_btn.setGeometry(QtCore.QRect(410, 530, 161, 41))
        self.ayarlar_btn.setObjectName("ayarlar_btn")

        self.retranslateUi(StudentEntry)
        QtCore.QMetaObject.connectSlotsByName(StudentEntry)

    def retranslateUi(self, StudentEntry):
        _translate = QtCore.QCoreApplication.translate
        StudentEntry.setWindowTitle(_translate("StudentEntry", "Ogrenci Giris Ekrani "))
        self.zayifKonu_btn.setText(_translate("StudentEntry", "Zayıf konular sınav modülü"))
        self.sigma_btn.setText(_translate("StudentEntry", "6 sigma sınav modülü"))
        self.istatistik_btn.setText(_translate("StudentEntry", "Istatistiklerim"))
        self.ayarlar_btn.setText(_translate("StudentEntry", "Ayarlar"))
